export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const CUSTOMER_SIGNUP = 'CUSTOMER_SIGNUP';
export const OWNER_SIGNUP = 'OWNER_SIGNUP';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const GET_OWNER = 'GET_OWNER';
export const UPDATE_OWNER = 'UPDATE_OWNER';