export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const CUSTOMER_SIGNUP = 'CUSTOMER_SIGNUP';
export const RESTAURANT_SIGNUP = 'RESTAURANT_SIGNUP';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const GET_RESTAURANT = 'GET_RESTAURANT';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';